/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : ../output/glitchFilterTMR.v                                                            *
 *                                                                                                  *
 * user    : qsun                                                                                   *
 * host    : sphy7asic02.smu.edu                                                                    *
 * date    : 24/01/2022 12:04:51                                                                    *
 *                                                                                                  *
 * workdir : /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/i2c_backend_v5/tmr/work           *
 * cmd     : /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/tmrg/bin/tmrg --log tmrg.log      *
 *           --include --inc-dir /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/git1/etroc2/rtl *
 *           --lib ../simplified_std_cell_lib.v --lib                                               *
 *           /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/git1/etroc2/libs/powerOnResetLong.v *
 *           --lib /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/git1/etroc2/libs/IO_1P2V_C4.v *
 *           --lib                                                                                  *
 *           /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/git1/etroc2/libs/customDigitalLib.v *
 *           -c ../config/tmrg.cnf                                                                  *
 * tmrg rev:                                                                                        *
 *                                                                                                  *
 * src file: /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/git2/etroc2/rtl/glitchFilter.v    *
 *           File is NOT under version control!                                                     *
 *           Modification time : 2022-01-20 11:51:38.804700                                         *
 *           File Size         : 962                                                                *
 *           MD5 hash          : c33732c188dd8fdaf5dbe80b0ac46c77                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`timescale  1ps/1ps
module glitchFilter(
     input  in,
     output  out
);
wire inDel0;
wire inDel1;
wire inDel2;
wire inDel3;

DEL4WRAPPER DL0 (
          .I(in),
          .Z(inDel0)
          );

DEL4WRAPPER DL1 (
          .I(inDel0),
          .Z(inDel1)
          );

DEL4WRAPPER DL2 (
          .I(inDel1),
          .Z(inDel2)
          );

DEL4WRAPPER DL3 (
          .I(inDel2),
          .Z(inDel3)
          );

AO222D4GF and_or_preserve (
          .A1(in),
          .A2(inDel3),
          .B1(in),
          .B2(out),
          .C1(inDel3),
          .C2(out),
          .Z(out)
          );
endmodule

