//`include "./rtl/ETROC_PLL_Core_tb.v"			// testbench

`include "./rtl/ETROC_PLL_Core.v"
`include "./rtl/ETROC_PLL_Core_noAFC.v"
`include "./rtl/LJCDR.vams"
`include "./rtl/vco_m.va"
`include "./rtl/pfd_cp_m.vams"
`include "./rtl/lpf_m.va"
`include "./rtl/PFD_INSTLOCK.v"
`include "./rtl/bit_protector.v"
`include "./rtl/feedbackDividerTMR.v"
`include "./rtl/freqDividerSamplerTMR.v"
`include "./rtl/lpgbt_clkgen_wbias.vams"
`include "./rtl/AFC4ChV2.v"
`include "./rtl/AFCfsm_TMR.v"
`include "./rtl/AFCfsm_tmrblock.v"
`include "./rtl/asyncCounter.v"
`include "./rtl/voter.v"
`include "./rtl/voter3bit.v"
`include "./rtl/voter6bit.v"
`include "./rtl/bin2thermo3bits.v"
`include "./rtl/thermo2bin6bits.v"
`include "./rtl/voter4bit.v"
`include "./rtl/ETROC1_HsLib.v"
`include "./rtl/DDFKLND1_LVT_ELT.v"
`include "./rtl/majorityVoterBalanced.v"
`include "./rtl/majorityVoter.v"
//`include "./rtl/freqPrescalerTMR.v"
`include "./rtl/freqPrescalerTMR_Simplified.v"
`include "./rtl/DELKLND1_LVT_ELT.v"
//`include "./rtl/"
//`include "./rtl/"


