//`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/ETROC_PLL_Core_tb.v"			// testbench

`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/ETROC_PLL_Core.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/ETROC_PLL_Core_noAFC.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/LJCDR.vams"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/vco_m.va"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/pfd_cp_m.vams"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/lpf_m.va"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/PFD_INSTLOCK.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/bit_protector.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/feedbackDividerTMR.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/freqDividerSamplerTMR.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/lpgbt_clkgen_wbias.vams"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/AFC4ChV2.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/AFCfsm_TMR.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/AFCfsm_tmrblock.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/asyncCounter.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/voter.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/voter3bit.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/voter6bit.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/bin2thermo3bits.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/thermo2bin6bits.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/voter4bit.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/ETROC1_HsLib.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/DDFKLND1_LVT_ELT.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/majorityVoterBalanced.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/majorityVoter.v"
//`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/freqPrescalerTMR.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/freqPrescalerTMR_Simplified.v"
`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/DELKLND1_LVT_ELT.v"
//`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/"
//`include "/users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC_PLL_model/rtl/"


