/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : ../output/DEL4WRAPPERTMR.v                                                             *
 *                                                                                                  *
 * user    : qsun                                                                                   *
 * host    : hepasic2.physics.smu.edu                                                               *
 * date    : 01/07/2021 17:52:01                                                                    *
 *                                                                                                  *
 * workdir : /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC2_TH_Ctrl/tmr/work           *
 * cmd     : /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/tmrg/bin/tmrg --log tmrg.log      *
 *           --include --inc-dir ../../ETROC_TH_Ctrl-main/ --lib ../simplified_std_cell_lib.v --lib *
 *           ../../ETROC_TH_Ctrl-main/powerOnResetLong.v --lib ../../libs/customDigitalLib.v -c     *
 *           ../config/tmrg.cnf                                                                     *
 * tmrg rev:                                                                                        *
 *                                                                                                  *
 * src file: ../../ETROC_TH_Ctrl-main/DEL4WRAPPER.v                                                 *
 *           File is NOT under version control!                                                     *
 *           Modification time : 2021-06-17 11:00:24.058339                                         *
 *           File Size         : 259                                                                *
 *           MD5 hash          : 587119bdc5d3cb13e48bb17393ada467                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`timescale  1ns / 1ps
module DEL4WRAPPER_THCtrl(
     input  I,
     output  Z
);
`ifdef  SIM
assign #(2:3:4) Z =  I;
`else 

DEL4 DL (
          .I(I),
          .Z(Z)
          );
`endif 
endmodule

