/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : ../output/glitchFilterTMR.v                                                            *
 *                                                                                                  *
 * user    : qsun                                                                                   *
 * host    : hepasic2.physics.smu.edu                                                               *
 * date    : 01/07/2021 17:52:02                                                                    *
 *                                                                                                  *
 * workdir : /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/ETROC2_TH_Ctrl/tmr/work           *
 * cmd     : /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/tmrg/bin/tmrg --log tmrg.log      *
 *           --include --inc-dir ../../ETROC_TH_Ctrl-main/ --lib ../simplified_std_cell_lib.v --lib *
 *           ../../ETROC_TH_Ctrl-main/powerOnResetLong.v --lib ../../libs/customDigitalLib.v -c     *
 *           ../config/tmrg.cnf                                                                     *
 * tmrg rev:                                                                                        *
 *                                                                                                  *
 * src file: ../../ETROC_TH_Ctrl-main/glitchFilter.v                                                *
 *           File is NOT under version control!                                                     *
 *           Modification time : 2021-06-28 19:13:24.184785                                         *
 *           File Size         : 963                                                                *
 *           MD5 hash          : 455718ddae8d7c0140a36cba70310894                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`timescale  1ps/1ps
module glitchFilter(
     input  in,
     output  out
);
wire inDel0;
wire inDel1;
wire inDel2;
wire inDel3;

DEL4WRAPPER_THCtrl DL0 (
          .I(in),
          .Z(inDel0)
          );

DEL4WRAPPER_THCtrl DL1 (
          .I(inDel0),
          .Z(inDel1)
          );

DEL4WRAPPER_THCtrl DL2 (
          .I(inDel1),
          .Z(inDel2)
          );

DEL4WRAPPER_THCtrl DL3 (
          .I(inDel2),
          .Z(inDel3)
          );

AO222D4GF and_or_preserve (
          .A1(in),
          .A2(inDel3),
          .B1(in),
          .B2(out),
          .C1(inDel3),
          .C2(out),
          .Z(out)
          );
endmodule

