/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : ./pixelTMR2/gateClockCellTMR.v                                                         *
 *                                                                                                  *
 * user    : dataogong                                                                              *
 * host    : 16-11005.local                                                                         *
 * date    : 05/05/2021 23:50:20                                                                    *
 *                                                                                                  *
 * workdir : /Users/dataogong/Documents/Gitlab/ETROCI2C/etroc2_swreadout/rtl/ETROC2Readout          *
 * cmd     : /Users/dataogong/Documents/ActiveDocument/Gitlab/tmrg/bin/tmrg -c tmrgPixel2.cnf       *
 * tmrg rev: e2867c77ccb74667bff8dd6a91891cdefaaa0580                                               *
 *                                                                                                  *
 * src file: gateClockCell.v                                                                        *
 *           File is NOT under version control!                                                     *
 *           Modification time : 2021-05-05 22:39:11.079918                                         *
 *           File Size         : 967                                                                *
 *           MD5 hash          : 78b63bcf48107c1c829fde0241b16171                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`timescale  1ns / 100ps
module gateClockCellTMR(
     input  clk,
     input  gate,
     input  enableGate,
     output  gatedClk
);

`ifdef SYNTHESIS
    CKLNQD1 CG_wrapper_inst(
        .Q(gatedClk),
        .CP(clk),
        .E(gate),
        .TE(~enableGate)
    );
`else
    reg  gateReg;
    always @( * )
    begin
        if (!clk)
        begin
            gateReg =  gate|!enableGate;
        end
    end
    assign gatedClk =  gateReg&clk;
 `endif

endmodule

