//all verilog files needed for globalDigital.v
`include "./etroc2readout/commonDefinition.v"
`include "./etroc2readout/digitalPhaseshifter.v"
`include "./etroc2readout/globalReadout_rtl.v"
`include "./etroc2readout/globalDigital.v"
`include "./etroc2readout/columnConnecter.v"
`include "./etroc2readout/dataSourceSwitcher.v"
`include "./etroc2readout/fastcommand/fastCommandDecoderTop.v"
`include "./etroc2readout/fastcommand/bitCLKAligner.v"
`include "./etroc2readout/fastcommand/bitclkgen.v"
`include "./etroc2readout/fastcommand/Arbiter.v"
`include "./etroc2readout/fastcommand/phaseAdjuster.v"
`include "./etroc2readout/fastcommand/DELWRAPPER.v"
`include "./etroc2readout/fastcommand/WADecoder.v"
`include "./etroc2readout/fastcommand/decoderHamming8to4.v"
`include "./etroc2readout/chargeInjectionPulseGen.v"
`include "./etroc2readout/globalController.v"
