//all verilog files needed for pixelDigitalTMR.v

//`include "./etroc2readout/globalDigitalTMR/commonDefinitionTMR.v"
//`include "./etroc2readout/globalDigitalTMR/majorityVoter.v"
//`include "./etroc2readout/globalDigitalTMR/voter.v"


//the three files shared with pixelReadout
//`include "./etroc2readout/pixelReadoutTMR/BCIDCounterTMR.v"
//`include "./etroc2readout/pixelReadoutTMR/PRBS31TMR.v"
//`include "./etroc2readout/pixelReadoutTMR/TestL1GeneratorTMR.v"
`include "./etroc2readout/lockDetector/ljCDRlockFilterDetectorTMR.v"
`include "./etroc2readout/globalDigitalTMR/ArbiterTMR.v"
`include "./etroc2readout/globalDigitalTMR/BCIDBufferTMR.v"
`include "./etroc2readout/globalDigitalTMR/BCID_mem_rtlTMR.v"
`include "./etroc2readout/globalDigitalTMR/globalControllerTMR.v"
`include "./etroc2readout/globalDigitalTMR/CRC8TMR.v"
`include "./etroc2readout/globalDigitalTMR/CircularBufferAddrTMR.v"
`include "./etroc2readout/globalDigitalTMR/DELWRAPPERTMR.v"
`include "./etroc2readout/globalDigitalTMR/FIFOWRCtrlerDDRTMR.v"
`include "./etroc2readout/globalDigitalTMR/FIFOWRCtrlerTMR.v"
`include "./etroc2readout/globalDigitalTMR/L1BufferAddrTMR.v"
`include "./etroc2readout/globalDigitalTMR/PRBS7TMR.v"
// `include "./etroc2readout/globalDigitalTMR/SWCellTMR.v"
`include "./etroc2readout/globalDigitalTMR/ScramblerTMR.v"
`include "./etroc2readout/globalDigitalTMR/SerializerTMR.v"
`include "./etroc2readout/globalDigitalTMR/WADecoderTMR.v"
`include "./etroc2readout/globalDigitalTMR/bitCLKAlignerTMR.v"
`include "./etroc2readout/globalDigitalTMR/bitclkgenTMR.v"
`include "./etroc2readout/globalDigitalTMR/cb_data_mem_decoderTMR.v"
`include "./etroc2readout/globalDigitalTMR/chargeInjectionPulseGenTMR.v"
`include "./etroc2readout/globalDigitalTMR/columnConnecterTMR.v"
`include "./etroc2readout/globalDigitalTMR/dataSourceSwitcherTMR.v"
`include "./etroc2readout/globalDigitalTMR/decoderHamming8to4TMR.v"
`include "./etroc2readout/globalDigitalTMR/digitalPhaseshifterTMR.v"
`include "./etroc2readout/globalDigitalTMR/fastCommandDecoderTopTMR.v"
`include "./etroc2readout/globalDigitalTMR/frameBuilderTMR.v"
// `include "./etroc2readout/globalDigitalTMR/globalDigitalTMR.v"
`include "./etroc2readout/globalDigitalTMR/globalDigitalTMR_pwr.v"
`include "./etroc2readout/globalDigitalTMR/globalReadoutControllerTMR.v"
`include "./etroc2readout/globalDigitalTMR/globalReadoutTMR.v"
// `include "./etroc2readout/globalDigitalTMR/latchedBasedRAMTMR.v"
`include "./etroc2readout/globalDigitalTMR/phaseAdjusterTMR.v"
`include "./etroc2readout/globalDigitalTMR/serializerBlockTMR.v"
`include "./etroc2readout/globalDigitalTMR/streamBufferTMR.v"
`include "./etroc2readout/globalDigitalTMR/streambuf_mem_rtlTMR.v"
`include "./etroc2readout/globalDigitalTMR/triggerProcessorTMR.v"
