//all verilog files needed for globalReadout.v
`include "./etroc2readout/commonDefinition.v"
`include "./etroc2readout/globalReadout.v"
`include "./etroc2readout/globalReadoutController.v"
`include "./etroc2readout/TestL1Generator.v"
`include "./etroc2readout/BCIDBuffer.v"
`include "./etroc2readout/memBlock/BCID_mem_rtl.v"
`include "./etroc2readout/BCIDCounter.v"
`include "./etroc2readout/CRC8.v"
`include "./etroc2readout/memBlock/cb_data_mem_decoder.v"
`include "./etroc2readout/L1BufferAddr.v"
`include "./etroc2readout/CircularBufferAddr.v"
`include "./etroc2readout/triggerProcessor.v"
`include "./etroc2readout/latchedBasedRAM.v"
`include "./etroc2readout/frameBuilder.v"
`include "./etroc2readout/FIFOWRCtrler.v"
`include "./etroc2readout/PRBS31.v"
`include "./etroc2readout/Serializer.v"
`include "./etroc2readout/serializerBlock.v"
`include "./etroc2readout/streamBuffer.v"
`include "./etroc2readout/memBlock/streambuf_mem_rtl.v"
`include "./etroc2readout/Scrambler.v"
`include "./etroc2readout/FIFOWRCtrlerDDR.v"

// `include "./etroc2readout/memBlock/BCID_mem.v"
// `include "./etroc2readout/CircularBuffer.v"
// `include "./etroc2readout/DataExtract.v"
// `include "./etroc2readout/DataExtractUnit.v"
// `include "./etroc2readout/Descrambler.v"
// `include "./etroc2readout/Deserializer.v"
// `include "./etroc2readout/DeserializerWithTriggerData.v"
// `include "./etroc2readout/L1EventBuffer.v"
// `include "./etroc2readout/memBlock/L1_data_mem.v"
// `include "./etroc2readout/memBlock/L1_hit_mem.v"
// `include "./etroc2readout/memBlock/L1_hit_mem_rtl.v"
// `include "./etroc2readout/PRBS7.v"
// `include "./etroc2readout/SWCell.v"
// `include "./etroc2readout/SixteenColChain.v"
// `include "./etroc2readout/TDCTestPatternGen.v"
// `include "./etroc2readout/memBlock/cb_data_mem.v"
// `include "./etroc2readout/memBlock/cb_data_mem_rtl.v"
// `include "./etroc2readout/memBlock/cb_hit_mem8.v"
// `include "./etroc2readout/memBlock/cb_hit_mem8_rtl.v"
// `include "./etroc2readout/columnAdapter.v"
// `include "./etroc2readout/columnAdapterChain.v"
// `include "./etroc2readout/dataRecordCheck.v"
// `include "./etroc2readout/delayLine.v"
// `include "./etroc2readout/finalDataCheck.v"
// `include "./etroc2readout/gateClockCell.v"
// `include "./etroc2readout/globalReadout_tb.v"
// `include "./etroc2readout/hitSRAMCircularBuffer.v"
// `include "./etroc2readout/hitSRAML1Buffer.v"
// `include "./etroc2readout/multiplePixelL1TDCDataCheck.v"
// `include "./etroc2readout/pixelReadout.v"
// `include "./etroc2readout/pixelReadoutCol.v"
// `include "./etroc2readout/pixelReadoutWithSWCell.v"
// `include "./etroc2readout/sram_rf_model.v"
// `include "./etroc2readout/memBlock/streambuf_mem.v"
// `include "./etroc2readout/pulseGenerator.v"
// `include "./etroc2readout/DELWRAPPER.v"
// `include "./etroc2readout/CW_ram_r_w_a_lat.v"


