set sdc_version 1.3

set tmrgSucces 0
set tmrgFailed 0
proc constrainNet netName {
  global tmrgSucces
  global tmrgFailed
  # find nets matching netName pattern
  set nets [dc::get_net $netName]
  if {[llength $nets] != 0} {
    set_dont_touch $nets
    incr tmrgSucces
  } else {
    puts "\[TMRG\] Warning! Net(s) '$netName' not found"
    incr tmrgFailed
  }
}

constrainNet /chargeInjection
constrainNet /chargeInjectionA
constrainNet /chargeInjectionB
constrainNet /chargeInjectionC
constrainNet /colBCSTChainA[*]
constrainNet /colBCSTChainB[*]
constrainNet /colBCSTChainC[*]
constrainNet /colBCSTChain[*]
constrainNet /colDataChainA[*]
constrainNet /colDataChainB[*]
constrainNet /colDataChainC[*]
constrainNet /colDataChain[*]
constrainNet /colHitChainA[*]
constrainNet /colHitChainB[*]
constrainNet /colHitChainC[*]
constrainNet /colHitChain[*]
constrainNet /colReadChainA[*]
constrainNet /colReadChainB[*]
constrainNet /colReadChainC[*]
constrainNet /colReadChain[*]
constrainNet /cpgInst/nextCountA[*]
constrainNet /cpgInst/nextCountB[*]
constrainNet /cpgInst/nextCountC[*]
constrainNet /cpgInst/nextCountVotedA[*]
constrainNet /cpgInst/nextCountVotedB[*]
constrainNet /cpgInst/nextCountVotedC[*]
constrainNet /cpgInst/nextsessionCountA[*]
constrainNet /cpgInst/nextsessionCountB[*]
constrainNet /cpgInst/nextsessionCountC[*]
constrainNet /cpgInst/nextsessionCountVotedA[*]
constrainNet /cpgInst/nextsessionCountVotedB[*]
constrainNet /cpgInst/nextsessionCountVotedC[*]
constrainNet /dgpInst/nextCountA[*]
constrainNet /dgpInst/nextCountB[*]
constrainNet /dgpInst/nextCountC[*]
constrainNet /dgpInst/nextCountVotedA[*]
constrainNet /dgpInst/nextCountVotedB[*]
constrainNet /dgpInst/nextCountVotedC[*]
constrainNet /fastCommandDecoderTop_inst/CLKAligner_Inst/bitclkgen_inst/nextCountA[*]
constrainNet /fastCommandDecoderTop_inst/CLKAligner_Inst/bitclkgen_inst/nextCountB[*]
constrainNet /fastCommandDecoderTop_inst/CLKAligner_Inst/bitclkgen_inst/nextCountC[*]
constrainNet /fastCommandDecoderTop_inst/CLKAligner_Inst/bitclkgen_inst/nextCountVotedA[*]
constrainNet /fastCommandDecoderTop_inst/CLKAligner_Inst/bitclkgen_inst/nextCountVotedB[*]
constrainNet /fastCommandDecoderTop_inst/CLKAligner_Inst/bitclkgen_inst/nextCountVotedC[*]
constrainNet /fastCommandDecoderTop_inst/CLKAligner_Inst/stateA[*]
constrainNet /fastCommandDecoderTop_inst/CLKAligner_Inst/stateB[*]
constrainNet /fastCommandDecoderTop_inst/CLKAligner_Inst/stateC[*]
constrainNet /fastCommandDecoderTop_inst/CLKAligner_Inst/stateVotedA[*]
constrainNet /fastCommandDecoderTop_inst/CLKAligner_Inst/stateVotedB[*]
constrainNet /fastCommandDecoderTop_inst/CLKAligner_Inst/stateVotedC[*]
constrainNet /fastCommandDecoderTop_inst/WADecoder_inst/cntNextA[*]
constrainNet /fastCommandDecoderTop_inst/WADecoder_inst/cntNextB[*]
constrainNet /fastCommandDecoderTop_inst/WADecoder_inst/cntNextC[*]
constrainNet /fastCommandDecoderTop_inst/WADecoder_inst/cntNextVotedA[*]
constrainNet /fastCommandDecoderTop_inst/WADecoder_inst/cntNextVotedB[*]
constrainNet /fastCommandDecoderTop_inst/WADecoder_inst/cntNextVotedC[*]
constrainNet /fastCommandDecoderTop_inst/nextCountA[*]
constrainNet /fastCommandDecoderTop_inst/nextCountB[*]
constrainNet /fastCommandDecoderTop_inst/nextCountC[*]
constrainNet /fastCommandDecoderTop_inst/nextCountVotedA[*]
constrainNet /fastCommandDecoderTop_inst/nextCountVotedB[*]
constrainNet /fastCommandDecoderTop_inst/nextCountVotedC[*]
constrainNet /fcData
constrainNet /fcDataA
constrainNet /fcDataB
constrainNet /fcDataC
constrainNet /leftGlobalReadout/BC/nextBCIDA[*]
constrainNet /leftGlobalReadout/BC/nextBCIDB[*]
constrainNet /leftGlobalReadout/BC/nextBCIDC[*]
constrainNet /leftGlobalReadout/BC/nextBCIDVotedA[*]
constrainNet /leftGlobalReadout/BC/nextBCIDVotedB[*]
constrainNet /leftGlobalReadout/BC/nextBCIDVotedC[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/AAA[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/AAB[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/AAC[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/AA[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/ABA[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/ABB[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/ABC[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/AB[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/CENA
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/CENAA
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/CENAB
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/CENAC
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/CENB
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/CENBA
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/CENBB
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/CENBC
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/CLKA
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/CLKAA
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/CLKAB
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/CLKAC
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/CLKB
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/CLKBA
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/CLKBB
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/CLKBC
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/COLLDISN
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/COLLDISNA
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/COLLDISNB
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/COLLDISNC
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/DBA[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/DBB[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/DBC[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/DB[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/EMAAA[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/EMAAB[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/EMAAC[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/EMAA[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/EMABA[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/EMABB[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/EMABC[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/EMAB[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/QAA[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/QAB[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/QAC[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/QA[*]
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/RET1N
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/RET1NA
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/RET1NB
constrainNet /leftGlobalReadout/BCB/BCIDB/u0/RET1NC
constrainNet /leftGlobalReadout/TPInst/nextOddA
constrainNet /leftGlobalReadout/TPInst/nextOddB
constrainNet /leftGlobalReadout/TPInst/nextOddC
constrainNet /leftGlobalReadout/TPInst/nextOddVotedA
constrainNet /leftGlobalReadout/TPInst/nextOddVotedB
constrainNet /leftGlobalReadout/TPInst/nextOddVotedC
constrainNet /leftGlobalReadout/TestL1GeneratorInst/nextCountA[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/nextCountB[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/nextCountC[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/nextCountVotedA[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/nextCountVotedB[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/nextCountVotedC[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/nextTriggerCountA[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/nextTriggerCountB[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/nextTriggerCountC[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/nextTriggerCountVotedA[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/nextTriggerCountVotedB[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/nextTriggerCountVotedC[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/prbs_inst/nextWordA[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/prbs_inst/nextWordB[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/prbs_inst/nextWordC[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/prbs_inst/nextWordVotedA[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/prbs_inst/nextWordVotedB[*]
constrainNet /leftGlobalReadout/TestL1GeneratorInst/prbs_inst/nextWordVotedC[*]
constrainNet /leftGlobalReadout/fbInst/dataRecordA[*]
constrainNet /leftGlobalReadout/fbInst/dataRecordB[*]
constrainNet /leftGlobalReadout/fbInst/dataRecordC[*]
constrainNet /leftGlobalReadout/fbInst/dataRecordVotedA[*]
constrainNet /leftGlobalReadout/fbInst/dataRecordVotedB[*]
constrainNet /leftGlobalReadout/fbInst/dataRecordVotedC[*]
constrainNet /leftGlobalReadout/fbInst/dataTypeA[*]
constrainNet /leftGlobalReadout/fbInst/dataTypeB[*]
constrainNet /leftGlobalReadout/fbInst/dataTypeC[*]
constrainNet /leftGlobalReadout/fbInst/dataTypeVotedA[*]
constrainNet /leftGlobalReadout/fbInst/dataTypeVotedB[*]
constrainNet /leftGlobalReadout/fbInst/dataTypeVotedC[*]
constrainNet /leftGlobalReadout/fbInst/eventStartA
constrainNet /leftGlobalReadout/fbInst/eventStartB
constrainNet /leftGlobalReadout/fbInst/eventStartC
constrainNet /leftGlobalReadout/fbInst/eventStartVotedA
constrainNet /leftGlobalReadout/fbInst/eventStartVotedB
constrainNet /leftGlobalReadout/fbInst/eventStartVotedC
constrainNet /leftGlobalReadout/fbInst/frameTrailerA[*]
constrainNet /leftGlobalReadout/fbInst/frameTrailerB[*]
constrainNet /leftGlobalReadout/fbInst/frameTrailerC[*]
constrainNet /leftGlobalReadout/fbInst/frameTrailerVotedA[*]
constrainNet /leftGlobalReadout/fbInst/frameTrailerVotedB[*]
constrainNet /leftGlobalReadout/fbInst/frameTrailerVotedC[*]
constrainNet /leftGlobalReadout/fbInst/hitA
constrainNet /leftGlobalReadout/fbInst/hitB
constrainNet /leftGlobalReadout/fbInst/hitC
constrainNet /leftGlobalReadout/fbInst/hitCountNextA[*]
constrainNet /leftGlobalReadout/fbInst/hitCountNextB[*]
constrainNet /leftGlobalReadout/fbInst/hitCountNextC[*]
constrainNet /leftGlobalReadout/fbInst/hitCountNextVotedA[*]
constrainNet /leftGlobalReadout/fbInst/hitCountNextVotedB[*]
constrainNet /leftGlobalReadout/fbInst/hitCountNextVotedC[*]
constrainNet /leftGlobalReadout/fbInst/hitVotedA
constrainNet /leftGlobalReadout/fbInst/hitVotedB
constrainNet /leftGlobalReadout/fbInst/hitVotedC
constrainNet /leftGlobalReadout/fbInst/nextCRCA[*]
constrainNet /leftGlobalReadout/fbInst/nextCRCB[*]
constrainNet /leftGlobalReadout/fbInst/nextCRCC[*]
constrainNet /leftGlobalReadout/fbInst/nextCRCVotedA[*]
constrainNet /leftGlobalReadout/fbInst/nextCRCVotedB[*]
constrainNet /leftGlobalReadout/fbInst/nextCRCVotedC[*]
constrainNet /leftGlobalReadout/fbInst/streamBufAlmostFullA
constrainNet /leftGlobalReadout/fbInst/streamBufAlmostFullB
constrainNet /leftGlobalReadout/fbInst/streamBufAlmostFullC
constrainNet /leftGlobalReadout/fbInst/streamBufAlmostFullVotedA
constrainNet /leftGlobalReadout/fbInst/streamBufAlmostFullVotedB
constrainNet /leftGlobalReadout/fbInst/streamBufAlmostFullVotedC
constrainNet /leftGlobalReadout/gbrcInst/CBAddrInst/CBwrAddrNextA[*]
constrainNet /leftGlobalReadout/gbrcInst/CBAddrInst/CBwrAddrNextB[*]
constrainNet /leftGlobalReadout/gbrcInst/CBAddrInst/CBwrAddrNextC[*]
constrainNet /leftGlobalReadout/gbrcInst/CBAddrInst/CBwrAddrNextVotedA[*]
constrainNet /leftGlobalReadout/gbrcInst/CBAddrInst/CBwrAddrNextVotedB[*]
constrainNet /leftGlobalReadout/gbrcInst/CBAddrInst/CBwrAddrNextVotedC[*]
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdAddrNextA[*]
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdAddrNextB[*]
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdAddrNextC[*]
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdAddrNextVotedA[*]
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdAddrNextVotedB[*]
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdAddrNextVotedC[*]
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyA
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyB
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyC
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyNextA
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyNextB
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyNextC
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyNextVotedA
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyNextVotedB
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyNextVotedC
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyVotedA
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyVotedB
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyVotedC
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdenA
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdenB
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdenC
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdenVotedA
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdenVotedB
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdenVotedC
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrAddrNextA[*]
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrAddrNextB[*]
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrAddrNextC[*]
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrAddrNextVotedA[*]
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrAddrNextVotedB[*]
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrAddrNextVotedC[*]
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullA
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullB
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullC
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullNextA
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullNextB
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullNextC
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullNextVotedA
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullNextVotedB
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullNextVotedC
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullVotedA
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullVotedB
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullVotedC
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrenA
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrenB
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrenC
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrenVotedA
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrenVotedB
constrainNet /leftGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrenVotedC
constrainNet /leftGlobalReadout/gbrcInst/L1BufEmptyA
constrainNet /leftGlobalReadout/gbrcInst/L1BufEmptyB
constrainNet /leftGlobalReadout/gbrcInst/L1BufEmptyC
constrainNet /leftGlobalReadout/gbrcInst/L1BufEmptyVotedA
constrainNet /leftGlobalReadout/gbrcInst/L1BufEmptyVotedB
constrainNet /leftGlobalReadout/gbrcInst/L1BufEmptyVotedC
constrainNet /leftGlobalReadout/gbrcInst/sessionStartNextA
constrainNet /leftGlobalReadout/gbrcInst/sessionStartNextB
constrainNet /leftGlobalReadout/gbrcInst/sessionStartNextC
constrainNet /leftGlobalReadout/gbrcInst/sessionStartNextVotedA
constrainNet /leftGlobalReadout/gbrcInst/sessionStartNextVotedB
constrainNet /leftGlobalReadout/gbrcInst/sessionStartNextVotedC
constrainNet /leftGlobalReadout/gbrcInst/streamBufAlmostFullA
constrainNet /leftGlobalReadout/gbrcInst/streamBufAlmostFullB
constrainNet /leftGlobalReadout/gbrcInst/streamBufAlmostFullC
constrainNet /leftGlobalReadout/gbrcInst/streamBufAlmostFullVotedA
constrainNet /leftGlobalReadout/gbrcInst/streamBufAlmostFullVotedB
constrainNet /leftGlobalReadout/gbrcInst/streamBufAlmostFullVotedC
constrainNet /leftGlobalReadout/nextL1CountA[*]
constrainNet /leftGlobalReadout/nextL1CountB[*]
constrainNet /leftGlobalReadout/nextL1CountC[*]
constrainNet /leftGlobalReadout/nextL1CountVotedA[*]
constrainNet /leftGlobalReadout/nextL1CountVotedB[*]
constrainNet /leftGlobalReadout/nextL1CountVotedC[*]
constrainNet /leftGlobalReadout/scrInst/rNextA[*]
constrainNet /leftGlobalReadout/scrInst/rNextB[*]
constrainNet /leftGlobalReadout/scrInst/rNextC[*]
constrainNet /leftGlobalReadout/scrInst/rNextVotedA[*]
constrainNet /leftGlobalReadout/scrInst/rNextVotedB[*]
constrainNet /leftGlobalReadout/scrInst/rNextVotedC[*]
constrainNet /leftGlobalReadout/serInst/clk1280
constrainNet /leftGlobalReadout/serInst/clk1280A
constrainNet /leftGlobalReadout/serInst/clk1280B
constrainNet /leftGlobalReadout/serInst/clk1280C
constrainNet /leftGlobalReadout/serInst/nextCounterA[*]
constrainNet /leftGlobalReadout/serInst/nextCounterB[*]
constrainNet /leftGlobalReadout/serInst/nextCounterC[*]
constrainNet /leftGlobalReadout/serInst/nextCounterVotedA[*]
constrainNet /leftGlobalReadout/serInst/nextCounterVotedB[*]
constrainNet /leftGlobalReadout/serInst/nextCounterVotedC[*]
constrainNet /leftGlobalReadout/serInst/prbs7_16/seedA[*]
constrainNet /leftGlobalReadout/serInst/prbs7_16/seedB[*]
constrainNet /leftGlobalReadout/serInst/prbs7_16/seedC[*]
constrainNet /leftGlobalReadout/serInst/prbs7_16/seedVotedA[*]
constrainNet /leftGlobalReadout/serInst/prbs7_16/seedVotedB[*]
constrainNet /leftGlobalReadout/serInst/prbs7_16/seedVotedC[*]
constrainNet /leftGlobalReadout/serInst/prbs7_32/seedA[*]
constrainNet /leftGlobalReadout/serInst/prbs7_32/seedB[*]
constrainNet /leftGlobalReadout/serInst/prbs7_32/seedC[*]
constrainNet /leftGlobalReadout/serInst/prbs7_32/seedVotedA[*]
constrainNet /leftGlobalReadout/serInst/prbs7_32/seedVotedB[*]
constrainNet /leftGlobalReadout/serInst/prbs7_32/seedVotedC[*]
constrainNet /leftGlobalReadout/serInst/prbs7_8/seedA[*]
constrainNet /leftGlobalReadout/serInst/prbs7_8/seedB[*]
constrainNet /leftGlobalReadout/serInst/prbs7_8/seedC[*]
constrainNet /leftGlobalReadout/serInst/prbs7_8/seedVotedA[*]
constrainNet /leftGlobalReadout/serInst/prbs7_8/seedVotedB[*]
constrainNet /leftGlobalReadout/serInst/prbs7_8/seedVotedC[*]
constrainNet /leftGlobalReadout/serInst/soutVoted
constrainNet /leftGlobalReadout/serInst/soutVotedA
constrainNet /leftGlobalReadout/serInst/soutVotedB
constrainNet /leftGlobalReadout/serInst/soutVotedC
constrainNet /leftGlobalReadout/streamBufferInst/almostEmptyA
constrainNet /leftGlobalReadout/streamBufferInst/almostEmptyB
constrainNet /leftGlobalReadout/streamBufferInst/almostEmptyC
constrainNet /leftGlobalReadout/streamBufferInst/almostEmptyVotedA
constrainNet /leftGlobalReadout/streamBufferInst/almostEmptyVotedB
constrainNet /leftGlobalReadout/streamBufferInst/almostEmptyVotedC
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/rdAddrNextA[*]
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/rdAddrNextB[*]
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/rdAddrNextC[*]
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/rdAddrNextVotedA[*]
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/rdAddrNextVotedB[*]
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/rdAddrNextVotedC[*]
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/rdenA
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/rdenB
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/rdenC
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/rdenVotedA
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/rdenVotedB
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/rdenVotedC
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/wrAddrNextA[*]
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/wrAddrNextB[*]
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/wrAddrNextC[*]
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/wrAddrNextVotedA[*]
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/wrAddrNextVotedB[*]
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/wrAddrNextVotedC[*]
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/wrenA
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/wrenB
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/wrenC
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/wrenVotedA
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/wrenVotedB
constrainNet /leftGlobalReadout/streamBufferInst/dataBufCtrl/wrenVotedC
constrainNet /leftGlobalReadout/streamBufferInst/loadDataA
constrainNet /leftGlobalReadout/streamBufferInst/loadDataB
constrainNet /leftGlobalReadout/streamBufferInst/loadDataC
constrainNet /leftGlobalReadout/streamBufferInst/loadDataVotedA
constrainNet /leftGlobalReadout/streamBufferInst/loadDataVotedB
constrainNet /leftGlobalReadout/streamBufferInst/loadDataVotedC
constrainNet /leftGlobalReadout/streamBufferInst/nextRdAddrA[*]
constrainNet /leftGlobalReadout/streamBufferInst/nextRdAddrB[*]
constrainNet /leftGlobalReadout/streamBufferInst/nextRdAddrC[*]
constrainNet /leftGlobalReadout/streamBufferInst/nextRdAddrVotedA[*]
constrainNet /leftGlobalReadout/streamBufferInst/nextRdAddrVotedB[*]
constrainNet /leftGlobalReadout/streamBufferInst/nextRdAddrVotedC[*]
constrainNet /leftGlobalReadout/streamBufferInst/nextWrAddrA[*]
constrainNet /leftGlobalReadout/streamBufferInst/nextWrAddrB[*]
constrainNet /leftGlobalReadout/streamBufferInst/nextWrAddrC[*]
constrainNet /leftGlobalReadout/streamBufferInst/nextWrAddrVotedA[*]
constrainNet /leftGlobalReadout/streamBufferInst/nextWrAddrVotedB[*]
constrainNet /leftGlobalReadout/streamBufferInst/nextWrAddrVotedC[*]
constrainNet /leftGlobalReadout/streamBufferInst/startA
constrainNet /leftGlobalReadout/streamBufferInst/startB
constrainNet /leftGlobalReadout/streamBufferInst/startC
constrainNet /leftGlobalReadout/streamBufferInst/startVotedA
constrainNet /leftGlobalReadout/streamBufferInst/startVotedB
constrainNet /leftGlobalReadout/streamBufferInst/startVotedC
constrainNet /readoutClock
constrainNet /readoutClockA
constrainNet /readoutClockB
constrainNet /readoutClockC
constrainNet /rightGlobalReadout/BC/nextBCIDA[*]
constrainNet /rightGlobalReadout/BC/nextBCIDB[*]
constrainNet /rightGlobalReadout/BC/nextBCIDC[*]
constrainNet /rightGlobalReadout/BC/nextBCIDVotedA[*]
constrainNet /rightGlobalReadout/BC/nextBCIDVotedB[*]
constrainNet /rightGlobalReadout/BC/nextBCIDVotedC[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/AAA[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/AAB[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/AAC[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/AA[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/ABA[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/ABB[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/ABC[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/AB[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/CENA
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/CENAA
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/CENAB
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/CENAC
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/CENB
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/CENBA
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/CENBB
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/CENBC
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/CLKA
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/CLKAA
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/CLKAB
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/CLKAC
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/CLKB
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/CLKBA
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/CLKBB
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/CLKBC
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/COLLDISN
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/COLLDISNA
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/COLLDISNB
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/COLLDISNC
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/DBA[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/DBB[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/DBC[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/DB[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/EMAAA[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/EMAAB[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/EMAAC[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/EMAA[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/EMABA[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/EMABB[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/EMABC[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/EMAB[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/QAA[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/QAB[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/QAC[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/QA[*]
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/RET1N
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/RET1NA
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/RET1NB
constrainNet /rightGlobalReadout/BCB/BCIDB/u0/RET1NC
constrainNet /rightGlobalReadout/TPInst/nextOddA
constrainNet /rightGlobalReadout/TPInst/nextOddB
constrainNet /rightGlobalReadout/TPInst/nextOddC
constrainNet /rightGlobalReadout/TPInst/nextOddVotedA
constrainNet /rightGlobalReadout/TPInst/nextOddVotedB
constrainNet /rightGlobalReadout/TPInst/nextOddVotedC
constrainNet /rightGlobalReadout/TestL1GeneratorInst/nextCountA[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/nextCountB[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/nextCountC[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/nextCountVotedA[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/nextCountVotedB[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/nextCountVotedC[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/nextTriggerCountA[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/nextTriggerCountB[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/nextTriggerCountC[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/nextTriggerCountVotedA[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/nextTriggerCountVotedB[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/nextTriggerCountVotedC[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/prbs_inst/nextWordA[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/prbs_inst/nextWordB[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/prbs_inst/nextWordC[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/prbs_inst/nextWordVotedA[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/prbs_inst/nextWordVotedB[*]
constrainNet /rightGlobalReadout/TestL1GeneratorInst/prbs_inst/nextWordVotedC[*]
constrainNet /rightGlobalReadout/fbInst/dataRecordA[*]
constrainNet /rightGlobalReadout/fbInst/dataRecordB[*]
constrainNet /rightGlobalReadout/fbInst/dataRecordC[*]
constrainNet /rightGlobalReadout/fbInst/dataRecordVotedA[*]
constrainNet /rightGlobalReadout/fbInst/dataRecordVotedB[*]
constrainNet /rightGlobalReadout/fbInst/dataRecordVotedC[*]
constrainNet /rightGlobalReadout/fbInst/dataTypeA[*]
constrainNet /rightGlobalReadout/fbInst/dataTypeB[*]
constrainNet /rightGlobalReadout/fbInst/dataTypeC[*]
constrainNet /rightGlobalReadout/fbInst/dataTypeVotedA[*]
constrainNet /rightGlobalReadout/fbInst/dataTypeVotedB[*]
constrainNet /rightGlobalReadout/fbInst/dataTypeVotedC[*]
constrainNet /rightGlobalReadout/fbInst/eventStartA
constrainNet /rightGlobalReadout/fbInst/eventStartB
constrainNet /rightGlobalReadout/fbInst/eventStartC
constrainNet /rightGlobalReadout/fbInst/eventStartVotedA
constrainNet /rightGlobalReadout/fbInst/eventStartVotedB
constrainNet /rightGlobalReadout/fbInst/eventStartVotedC
constrainNet /rightGlobalReadout/fbInst/frameTrailerA[*]
constrainNet /rightGlobalReadout/fbInst/frameTrailerB[*]
constrainNet /rightGlobalReadout/fbInst/frameTrailerC[*]
constrainNet /rightGlobalReadout/fbInst/frameTrailerVotedA[*]
constrainNet /rightGlobalReadout/fbInst/frameTrailerVotedB[*]
constrainNet /rightGlobalReadout/fbInst/frameTrailerVotedC[*]
constrainNet /rightGlobalReadout/fbInst/hitA
constrainNet /rightGlobalReadout/fbInst/hitB
constrainNet /rightGlobalReadout/fbInst/hitC
constrainNet /rightGlobalReadout/fbInst/hitCountNextA[*]
constrainNet /rightGlobalReadout/fbInst/hitCountNextB[*]
constrainNet /rightGlobalReadout/fbInst/hitCountNextC[*]
constrainNet /rightGlobalReadout/fbInst/hitCountNextVotedA[*]
constrainNet /rightGlobalReadout/fbInst/hitCountNextVotedB[*]
constrainNet /rightGlobalReadout/fbInst/hitCountNextVotedC[*]
constrainNet /rightGlobalReadout/fbInst/hitVotedA
constrainNet /rightGlobalReadout/fbInst/hitVotedB
constrainNet /rightGlobalReadout/fbInst/hitVotedC
constrainNet /rightGlobalReadout/fbInst/nextCRCA[*]
constrainNet /rightGlobalReadout/fbInst/nextCRCB[*]
constrainNet /rightGlobalReadout/fbInst/nextCRCC[*]
constrainNet /rightGlobalReadout/fbInst/nextCRCVotedA[*]
constrainNet /rightGlobalReadout/fbInst/nextCRCVotedB[*]
constrainNet /rightGlobalReadout/fbInst/nextCRCVotedC[*]
constrainNet /rightGlobalReadout/fbInst/streamBufAlmostFullA
constrainNet /rightGlobalReadout/fbInst/streamBufAlmostFullB
constrainNet /rightGlobalReadout/fbInst/streamBufAlmostFullC
constrainNet /rightGlobalReadout/fbInst/streamBufAlmostFullVotedA
constrainNet /rightGlobalReadout/fbInst/streamBufAlmostFullVotedB
constrainNet /rightGlobalReadout/fbInst/streamBufAlmostFullVotedC
constrainNet /rightGlobalReadout/gbrcInst/CBAddrInst/CBwrAddrNextA[*]
constrainNet /rightGlobalReadout/gbrcInst/CBAddrInst/CBwrAddrNextB[*]
constrainNet /rightGlobalReadout/gbrcInst/CBAddrInst/CBwrAddrNextC[*]
constrainNet /rightGlobalReadout/gbrcInst/CBAddrInst/CBwrAddrNextVotedA[*]
constrainNet /rightGlobalReadout/gbrcInst/CBAddrInst/CBwrAddrNextVotedB[*]
constrainNet /rightGlobalReadout/gbrcInst/CBAddrInst/CBwrAddrNextVotedC[*]
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdAddrNextA[*]
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdAddrNextB[*]
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdAddrNextC[*]
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdAddrNextVotedA[*]
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdAddrNextVotedB[*]
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdAddrNextVotedC[*]
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyA
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyB
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyC
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyNextA
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyNextB
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyNextC
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyNextVotedA
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyNextVotedB
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyNextVotedC
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyVotedA
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyVotedB
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdEmptyVotedC
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdenA
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdenB
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdenC
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdenVotedA
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdenVotedB
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/rdenVotedC
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrAddrNextA[*]
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrAddrNextB[*]
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrAddrNextC[*]
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrAddrNextVotedA[*]
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrAddrNextVotedB[*]
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrAddrNextVotedC[*]
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullA
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullB
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullC
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullNextA
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullNextB
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullNextC
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullNextVotedA
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullNextVotedB
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullNextVotedC
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullVotedA
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullVotedB
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrFullVotedC
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrenA
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrenB
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrenC
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrenVotedA
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrenVotedB
constrainNet /rightGlobalReadout/gbrcInst/L1BAddrInst/L1Ctrl/wrenVotedC
constrainNet /rightGlobalReadout/gbrcInst/L1BufEmptyA
constrainNet /rightGlobalReadout/gbrcInst/L1BufEmptyB
constrainNet /rightGlobalReadout/gbrcInst/L1BufEmptyC
constrainNet /rightGlobalReadout/gbrcInst/L1BufEmptyVotedA
constrainNet /rightGlobalReadout/gbrcInst/L1BufEmptyVotedB
constrainNet /rightGlobalReadout/gbrcInst/L1BufEmptyVotedC
constrainNet /rightGlobalReadout/gbrcInst/sessionStartNextA
constrainNet /rightGlobalReadout/gbrcInst/sessionStartNextB
constrainNet /rightGlobalReadout/gbrcInst/sessionStartNextC
constrainNet /rightGlobalReadout/gbrcInst/sessionStartNextVotedA
constrainNet /rightGlobalReadout/gbrcInst/sessionStartNextVotedB
constrainNet /rightGlobalReadout/gbrcInst/sessionStartNextVotedC
constrainNet /rightGlobalReadout/gbrcInst/streamBufAlmostFullA
constrainNet /rightGlobalReadout/gbrcInst/streamBufAlmostFullB
constrainNet /rightGlobalReadout/gbrcInst/streamBufAlmostFullC
constrainNet /rightGlobalReadout/gbrcInst/streamBufAlmostFullVotedA
constrainNet /rightGlobalReadout/gbrcInst/streamBufAlmostFullVotedB
constrainNet /rightGlobalReadout/gbrcInst/streamBufAlmostFullVotedC
constrainNet /rightGlobalReadout/nextL1CountA[*]
constrainNet /rightGlobalReadout/nextL1CountB[*]
constrainNet /rightGlobalReadout/nextL1CountC[*]
constrainNet /rightGlobalReadout/nextL1CountVotedA[*]
constrainNet /rightGlobalReadout/nextL1CountVotedB[*]
constrainNet /rightGlobalReadout/nextL1CountVotedC[*]
constrainNet /rightGlobalReadout/scrInst/rNextA[*]
constrainNet /rightGlobalReadout/scrInst/rNextB[*]
constrainNet /rightGlobalReadout/scrInst/rNextC[*]
constrainNet /rightGlobalReadout/scrInst/rNextVotedA[*]
constrainNet /rightGlobalReadout/scrInst/rNextVotedB[*]
constrainNet /rightGlobalReadout/scrInst/rNextVotedC[*]
constrainNet /rightGlobalReadout/serInst/clk1280
constrainNet /rightGlobalReadout/serInst/clk1280A
constrainNet /rightGlobalReadout/serInst/clk1280B
constrainNet /rightGlobalReadout/serInst/clk1280C
constrainNet /rightGlobalReadout/serInst/nextCounterA[*]
constrainNet /rightGlobalReadout/serInst/nextCounterB[*]
constrainNet /rightGlobalReadout/serInst/nextCounterC[*]
constrainNet /rightGlobalReadout/serInst/nextCounterVotedA[*]
constrainNet /rightGlobalReadout/serInst/nextCounterVotedB[*]
constrainNet /rightGlobalReadout/serInst/nextCounterVotedC[*]
constrainNet /rightGlobalReadout/serInst/prbs7_16/seedA[*]
constrainNet /rightGlobalReadout/serInst/prbs7_16/seedB[*]
constrainNet /rightGlobalReadout/serInst/prbs7_16/seedC[*]
constrainNet /rightGlobalReadout/serInst/prbs7_16/seedVotedA[*]
constrainNet /rightGlobalReadout/serInst/prbs7_16/seedVotedB[*]
constrainNet /rightGlobalReadout/serInst/prbs7_16/seedVotedC[*]
constrainNet /rightGlobalReadout/serInst/prbs7_32/seedA[*]
constrainNet /rightGlobalReadout/serInst/prbs7_32/seedB[*]
constrainNet /rightGlobalReadout/serInst/prbs7_32/seedC[*]
constrainNet /rightGlobalReadout/serInst/prbs7_32/seedVotedA[*]
constrainNet /rightGlobalReadout/serInst/prbs7_32/seedVotedB[*]
constrainNet /rightGlobalReadout/serInst/prbs7_32/seedVotedC[*]
constrainNet /rightGlobalReadout/serInst/prbs7_8/seedA[*]
constrainNet /rightGlobalReadout/serInst/prbs7_8/seedB[*]
constrainNet /rightGlobalReadout/serInst/prbs7_8/seedC[*]
constrainNet /rightGlobalReadout/serInst/prbs7_8/seedVotedA[*]
constrainNet /rightGlobalReadout/serInst/prbs7_8/seedVotedB[*]
constrainNet /rightGlobalReadout/serInst/prbs7_8/seedVotedC[*]
constrainNet /rightGlobalReadout/serInst/soutVoted
constrainNet /rightGlobalReadout/serInst/soutVotedA
constrainNet /rightGlobalReadout/serInst/soutVotedB
constrainNet /rightGlobalReadout/serInst/soutVotedC
constrainNet /rightGlobalReadout/streamBufferInst/almostEmptyA
constrainNet /rightGlobalReadout/streamBufferInst/almostEmptyB
constrainNet /rightGlobalReadout/streamBufferInst/almostEmptyC
constrainNet /rightGlobalReadout/streamBufferInst/almostEmptyVotedA
constrainNet /rightGlobalReadout/streamBufferInst/almostEmptyVotedB
constrainNet /rightGlobalReadout/streamBufferInst/almostEmptyVotedC
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/rdAddrNextA[*]
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/rdAddrNextB[*]
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/rdAddrNextC[*]
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/rdAddrNextVotedA[*]
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/rdAddrNextVotedB[*]
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/rdAddrNextVotedC[*]
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/rdenA
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/rdenB
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/rdenC
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/rdenVotedA
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/rdenVotedB
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/rdenVotedC
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/wrAddrNextA[*]
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/wrAddrNextB[*]
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/wrAddrNextC[*]
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/wrAddrNextVotedA[*]
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/wrAddrNextVotedB[*]
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/wrAddrNextVotedC[*]
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/wrenA
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/wrenB
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/wrenC
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/wrenVotedA
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/wrenVotedB
constrainNet /rightGlobalReadout/streamBufferInst/dataBufCtrl/wrenVotedC
constrainNet /rightGlobalReadout/streamBufferInst/loadDataA
constrainNet /rightGlobalReadout/streamBufferInst/loadDataB
constrainNet /rightGlobalReadout/streamBufferInst/loadDataC
constrainNet /rightGlobalReadout/streamBufferInst/loadDataVotedA
constrainNet /rightGlobalReadout/streamBufferInst/loadDataVotedB
constrainNet /rightGlobalReadout/streamBufferInst/loadDataVotedC
constrainNet /rightGlobalReadout/streamBufferInst/nextRdAddrA[*]
constrainNet /rightGlobalReadout/streamBufferInst/nextRdAddrB[*]
constrainNet /rightGlobalReadout/streamBufferInst/nextRdAddrC[*]
constrainNet /rightGlobalReadout/streamBufferInst/nextRdAddrVotedA[*]
constrainNet /rightGlobalReadout/streamBufferInst/nextRdAddrVotedB[*]
constrainNet /rightGlobalReadout/streamBufferInst/nextRdAddrVotedC[*]
constrainNet /rightGlobalReadout/streamBufferInst/nextWrAddrA[*]
constrainNet /rightGlobalReadout/streamBufferInst/nextWrAddrB[*]
constrainNet /rightGlobalReadout/streamBufferInst/nextWrAddrC[*]
constrainNet /rightGlobalReadout/streamBufferInst/nextWrAddrVotedA[*]
constrainNet /rightGlobalReadout/streamBufferInst/nextWrAddrVotedB[*]
constrainNet /rightGlobalReadout/streamBufferInst/nextWrAddrVotedC[*]
constrainNet /rightGlobalReadout/streamBufferInst/startA
constrainNet /rightGlobalReadout/streamBufferInst/startB
constrainNet /rightGlobalReadout/streamBufferInst/startC
constrainNet /rightGlobalReadout/streamBufferInst/startVotedA
constrainNet /rightGlobalReadout/streamBufferInst/startVotedB
constrainNet /rightGlobalReadout/streamBufferInst/startVotedC
constrainNet /trigHitsColumnA[*]
constrainNet /trigHitsColumnB[*]
constrainNet /trigHitsColumnC[*]
constrainNet /trigHitsColumn[*]


    puts "TMRG successful  $tmrgSucces failed $tmrgFailed"
