/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : ./globalDigitalTMR/phaseAdjusterTMR.v                                                  *
 *                                                                                                  *
 * user    : dtgong                                                                                 *
 * host    : sphy7asic01.smu.edu                                                                    *
 * date    : 03/04/2022 15:30:05                                                                    *
 *                                                                                                  *
 * workdir : /users/dtgong/workarea/tsmc65/ETLROC/digital/ETROC2Readout/gitlab/etroc2readout        *
 * cmd     : ../../tmrg/tmrg/bin/tmrg -c tmrgGlobal.cnf                                             *
 * tmrg rev:                                                                                        *
 *                                                                                                  *
 * src file: fastcommand/phaseAdjuster.v                                                            *
 *           File is NOT under version control!                                                     *
 *           Modification time : 2022-03-22 20:45:27.142554                                         *
 *           File Size         : 1092                                                               *
 *           MD5 hash          : 9cc4ccf82e68fab78e907bcd4314d6db                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`timescale  1ns / 1ps
module phaseAdjusterTMR(
     fcA,
     fcB,
     fcC,
     clk320A,
     clk320B,
     clk320C,
     fcOutA,
     fcOutB,
     fcOutC,
     clk320OutA,
     clk320OutB,
     clk320OutC,
     clkDelayEnA,
     clkDelayEnB,
     clkDelayEnC,
     fcDelayEnA,
     fcDelayEnB,
     fcDelayEnC
);
input fcA;
input fcB;
input fcC;
input clk320A;
input clk320B;
input clk320C;
output fcOutA;
output fcOutB;
output fcOutC;
output clk320OutA;
output clk320OutB;
output clk320OutC;
input clkDelayEnA;
input clkDelayEnB;
input clkDelayEnC;
input fcDelayEnA;
input fcDelayEnB;
input fcDelayEnC;
wire clk320DelayInA;
wire clk320DelayInB;
wire clk320DelayInC;
wire clk320DelayOutA;
wire clk320DelayOutB;
wire clk320DelayOutC;
assign clk320DelayInA =  clkDelayEnA ? clk320A : 1'b0;
assign clk320DelayInB =  clkDelayEnB ? clk320B : 1'b0;
assign clk320DelayInC =  clkDelayEnC ? clk320C : 1'b0;

DELWRAPPER DELWRAPPER_clk320_InstA (
          .I(clk320DelayInA),
          .Z(clk320DelayOutA)
          );

DELWRAPPER DELWRAPPER_clk320_InstB (
          .I(clk320DelayInB),
          .Z(clk320DelayOutB)
          );

DELWRAPPER DELWRAPPER_clk320_InstC (
          .I(clk320DelayInC),
          .Z(clk320DelayOutC)
          );
assign clk320OutA =  clkDelayEnA ? clk320DelayOutA : clk320A;
assign clk320OutB =  clkDelayEnB ? clk320DelayOutB : clk320B;
assign clk320OutC =  clkDelayEnC ? clk320DelayOutC : clk320C;
wire fcDelayA;
wire fcDelayB;
wire fcDelayC;
wire fcDelayInA;
wire fcDelayInB;
wire fcDelayInC;
assign fcDelayInA =  fcDelayEnA ? fcA : 1'b0;
assign fcDelayInB =  fcDelayEnB ? fcB : 1'b0;
assign fcDelayInC =  fcDelayEnC ? fcC : 1'b0;

DELWRAPPER DELWRAPPER_fc_InstA (
          .I(fcDelayInA),
          .Z(fcDelayA)
          );

DELWRAPPER DELWRAPPER_fc_InstB (
          .I(fcDelayInB),
          .Z(fcDelayB)
          );

DELWRAPPER DELWRAPPER_fc_InstC (
          .I(fcDelayInC),
          .Z(fcDelayC)
          );
assign fcOutA =  fcDelayEnA ? fcDelayA : fcA;
assign fcOutB =  fcDelayEnB ? fcDelayB : fcB;
assign fcOutC =  fcDelayEnC ? fcDelayC : fcC;
endmodule

