/****************************************************************************************************
 *                          ! THIS FILE WAS AUTO-GENERATED BY TMRG TOOL !                           *
 *                                   ! DO NOT EDIT IT MANUALLY !                                    *
 *                                                                                                  *
 * file    : ../output/clockGeneratorDelayElementTMR.v                                              *
 *                                                                                                  *
 * user    : qsun                                                                                   *
 * host    : sphy7asic02.smu.edu                                                                    *
 * date    : 24/01/2022 12:04:50                                                                    *
 *                                                                                                  *
 * workdir : /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/i2c_backend_v5/tmr/work           *
 * cmd     : /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/tmrg/bin/tmrg --log tmrg.log      *
 *           --include --inc-dir /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/git1/etroc2/rtl *
 *           --lib ../simplified_std_cell_lib.v --lib                                               *
 *           /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/git1/etroc2/libs/powerOnResetLong.v *
 *           --lib /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/git1/etroc2/libs/IO_1P2V_C4.v *
 *           --lib                                                                                  *
 *           /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/git1/etroc2/libs/customDigitalLib.v *
 *           -c ../config/tmrg.cnf                                                                  *
 * tmrg rev:                                                                                        *
 *                                                                                                  *
 * src file: /users/qsun/workarea/tsmc65nm/ETROC_PLL/digital_work/git2/etroc2/rtl/clockGeneratorDelayElement.v *
 *           File is NOT under version control!                                                     *
 *           Modification time : 2022-01-20 11:50:53.437707                                         *
 *           File Size         : 723                                                                *
 *           MD5 hash          : c881442bf32af6adad86161148f0ae3f                                   *
 *                                                                                                  *
 ****************************************************************************************************/

`timescale  1ns/1ns
module clockGeneratorDelayElementTMR(
     clkInA,
     clkInB,
     clkInC,
     clkOutA,
     clkOutB,
     clkOutC
);
parameter    DelayCellsPerElement=4;
wor clkInTmrErrorC;
wire clkInVotedC;
wor clkInTmrErrorB;
wire clkInVotedB;
wor clkInTmrErrorA;
wire clkInVotedA;
input clkInA;
input clkInB;
input clkInC;
output clkOutA;
output clkOutB;
output clkOutC;
wire [DelayCellsPerElement:0] clkDelayedA;
wire [DelayCellsPerElement:0] clkDelayedB;
wire [DelayCellsPerElement:0] clkDelayedC;
assign clkDelayedA[0]  =  clkInVotedA;
assign clkDelayedB[0]  =  clkInVotedB;
assign clkDelayedC[0]  =  clkInVotedC;
assign clkOutA =  clkDelayedA[DelayCellsPerElement] ;
assign clkOutB =  clkDelayedB[DelayCellsPerElement] ;
assign clkOutC =  clkDelayedC[DelayCellsPerElement] ;
genvar i;

generate
     for(i =  0;i<DelayCellsPerElement;i =  i+1)
          begin : DEL 

               DEL4WRAPPER delayCellA (
                         .I(clkDelayedA[i] ),
                         .Z(clkDelayedA[i+1] )
                         );

               DEL4WRAPPER delayCellB (
                         .I(clkDelayedB[i] ),
                         .Z(clkDelayedB[i+1] )
                         );

               DEL4WRAPPER delayCellC (
                         .I(clkDelayedC[i] ),
                         .Z(clkDelayedC[i+1] )
                         );
          end

endgenerate

majorityVoterTag clkInVoterA (
          .inA(clkInA),
          .inB(clkInB),
          .inC(clkInC),
          .out(clkInVotedA),
          .tmrErr(clkInTmrErrorA)
          );

majorityVoterTag clkInVoterB (
          .inA(clkInA),
          .inB(clkInB),
          .inC(clkInC),
          .out(clkInVotedB),
          .tmrErr(clkInTmrErrorB)
          );

majorityVoterTag clkInVoterC (
          .inA(clkInA),
          .inB(clkInB),
          .inC(clkInC),
          .out(clkInVotedC),
          .tmrErr(clkInTmrErrorC)
          );
endmodule

