`include "ETROC2/functional/peripheryTMR/model/peripheryTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/i2cSlaveTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/resetVoterTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/glitchFilterTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/DEL4WRAPPERTMR_SIM.v"
    `include "ETROC2/functional/peripheryTMR/model/clockGeneratorTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/registerFileTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/memoryOutputMuxTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/memoryErrorCounterTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/testOutMuxTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/busMatrixAdapterTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/memoryAddrDecTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/testOutMuxChnTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/memoryCellTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/clockGeneratorDelayElementTMR.v"
    // `include "ETROC2/functional/peripheryTMR/model/fanoutGlitchFilterTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/glitchFilterTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/majorityVoterTagGatesTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/TAG3GATESTMR.v"
    `include "ETROC2/functional/peripheryTMR/model/majorityVoterTag.v"
    `include "ETROC2/functional/peripheryTMR/model/TAG3GATES.v"
    `include "ETROC2/functional/peripheryTMR/model/fanout.v"
    // `include "ETROC2/functional/peripheryTMR/model/customDigitalLib.v"
    `include "ETROC2/functional/POR/model/powerOnResetLong.v"
